version: "3.9"
volumes:
  node_modules:
  build:
  nfs_pg_data: {}
services:
  nfs-postgres:
    image: postgres:latest
    environment:
    - POSTGRES_USER=${POSTGRES_USER}
    - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
    volumes:
      - nfs_pg_data:/var/lib/postgresql/data
    ports:
      - "5779:5432"
  nfs-mosquitto:
    build: ./config/mosquitto
    image: eclipse-mosquitto
    restart: always
    ports:
      - "1883:1883"
    environment:
      - MOSQUITTO_USERNAME=${MOSQUITTO_USERNAME}
      - MOSQUITTO_PASSWORD=${MOSQUITTO_PASSWORD}
    volumes:
      - ./config/mosquitto/config:/mosquitto/config
      - ./config/mosquitto/data:/mosquitto/data
      - ./config/mosquitto/log:/mosquitto/log
  nfs-phoenix:
    tty: true
    stdin_open: true
    build: .
    environment:
      - PHX_ENV=dev
      - SECRET_KEY_BASE=${SECRET_KEY_BASE}
      - MOSQUITTO_SERVER=nfs-mosquitto
      - MOSQUITTO_USERNAME=${MOSQUITTO_USERNAME}
      - MOSQUITTO_PASSWORD=${MOSQUITTO_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_HOST=nfs-postgres
    volumes:
      - .:/app
      - node_modules:/app/assets/node_modules
      - build:/app/_build
    ports:
      - "4000:4000"
    depends_on:
      - nfs-postgres
      - nfs-mosquitto
  nfs-frame:
    tty: true
    stdin_open: true
    build: ./frontend/frame
    ports:
      - "3000:3000"
    volumes:
      - ./frontend/frame:/app
    depends_on:
      - nfs-phoenix
  nfs-server:
    image: nginx:latest
    volumes:
      - ./config/nginx/nginx.conf:/etc/nginx/conf.d/default.conf
    ports: 
      - "8888:8888"
    # command: /bin/bash -c "envsubst < /etc/nginx/conf.d/default.conf && nginx -g 'daemon off;'" 
    depends_on:
      - nfs-phoenix